import type { ConfigService } from '../services/contracts.js';
import type { InstanceConfig } from '../domain/types.js';
import { CA_OS_VERSION, CURRENT_SCHEMA_VERSION } from '../core/schema.js';
const env=((import.meta as unknown as {env?:Record<string,string|undefined>}).env??{});
export type InstanceBootstrap=Pick<InstanceConfig,'INSTANCE_ID'|'INSTANCE_NAME'|'DATA_PROVIDER'|'STORAGE_PROVIDER'>&Partial<Pick<InstanceConfig,'DATA_SOURCE_ID'|'ROOT_FOLDER_ID'|'GOOGLE_OAUTH_CLIENT_ID'>>;export interface DeploymentInstances{defaultInstanceId?:string;instances:InstanceBootstrap[];}
export const demoConfig=(instanceId='INSTANCE-DEMO'):InstanceConfig=>({INSTANCE_ID:instanceId,INSTANCE_NAME:instanceId==='INSTANCE-DEMO'?'DÉMO LOCALE':instanceId,INSTANCE_SCHEMA_VERSION:CURRENT_SCHEMA_VERSION,CA_OS_VERSION,COMPANY_ID:'ORG-000001',STORAGE_PROVIDER:'local',DATA_PROVIDER:'local',MAIL_PROVIDER:'none',CALENDAR_PROVIDER:'none',DOCUMENT_PROVIDER:'local',FEATURES:{AFFAIRES:true,ACTIONS:true,DECISIONS:true,DOCUMENTS:true,CONTACTS:true,EVENEMENTS:true}});
function fromBootstrap(b:InstanceBootstrap):InstanceConfig{return{...demoConfig(b.INSTANCE_ID),INSTANCE_NAME:b.INSTANCE_NAME,DATA_PROVIDER:b.DATA_PROVIDER,STORAGE_PROVIDER:b.STORAGE_PROVIDER,MAIL_PROVIDER:b.DATA_PROVIDER==='google'?'google':'none',CALENDAR_PROVIDER:b.DATA_PROVIDER==='google'?'google':'none',DOCUMENT_PROVIDER:b.DATA_PROVIDER==='google'?'google':'local',DATA_SOURCE_ID:b.DATA_SOURCE_ID,ROOT_FOLDER_ID:b.ROOT_FOLDER_ID,GOOGLE_OAUTH_CLIENT_ID:b.GOOGLE_OAUTH_CLIENT_ID};}
async function readStaticBootstrap():Promise<DeploymentInstances>{try{const r=await fetch('/caos.instances.json',{cache:'no-store'});if(!r.ok)return{instances:[]};const data=await r.json() as DeploymentInstances;return Array.isArray(data.instances)?data:{instances:[]};}catch{return{instances:[]};}}
function envBootstrap():InstanceBootstrap|undefined{const instanceId=String(env.VITE_CAOS_INSTANCE_ID??'').trim();const dataSourceId=String(env.VITE_CAOS_DATA_SOURCE_ID??'').trim();if(!instanceId||!dataSourceId)return;return{INSTANCE_ID:instanceId,INSTANCE_NAME:String(env.VITE_CAOS_INSTANCE_NAME??instanceId),DATA_PROVIDER:'google',STORAGE_PROVIDER:'google',DATA_SOURCE_ID:dataSourceId,ROOT_FOLDER_ID:String(env.VITE_CAOS_ROOT_FOLDER_ID??'').trim()||undefined,GOOGLE_OAUTH_CLIENT_ID:String(env.VITE_GOOGLE_OAUTH_CLIENT_ID??'').trim()||undefined};}
export class BrowserConfigService implements ConfigService{constructor(private readonly key='caos:active-config'){}async listDeploymentInstances(){const file=await readStaticBootstrap();const envOne=envBootstrap();if(envOne&&!file.instances.some(x=>x.INSTANCE_ID===envOne.INSTANCE_ID))file.instances.unshift(envOne);return file;}async get():Promise<InstanceConfig>{const deployment=await this.listDeploymentInstances();const envOne=envBootstrap();const selectedId=localStorage.getItem('caos:selected-instance')||deployment.defaultInstanceId||envOne?.INSTANCE_ID;const chosen=(selectedId&&deployment.instances.find(x=>x.INSTANCE_ID===selectedId))||envOne||deployment.instances[0];const base=chosen?fromBootstrap(chosen):demoConfig();const raw=localStorage.getItem(this.key);if(!raw)return base;try{const stored=JSON.parse(raw) as Partial<InstanceConfig>;if(chosen&&stored.INSTANCE_ID!==chosen.INSTANCE_ID)return{...base,GOOGLE_OAUTH_CLIENT_ID:stored.GOOGLE_OAUTH_CLIENT_ID||base.GOOGLE_OAUTH_CLIENT_ID};return{...base,...stored,INSTANCE_SCHEMA_VERSION:CURRENT_SCHEMA_VERSION,CA_OS_VERSION};}catch{return base;}}async selectDeploymentInstance(instanceId:string):Promise<InstanceConfig>{const deployment=await this.listDeploymentInstances();const target=deployment.instances.find(x=>x.INSTANCE_ID===instanceId);if(!target)throw new Error(`Instance non déclarée: ${instanceId}`);const previous=await this.get();const next={...fromBootstrap(target),GOOGLE_OAUTH_CLIENT_ID:previous.GOOGLE_OAUTH_CLIENT_ID};localStorage.setItem('caos:selected-instance',instanceId);localStorage.setItem(this.key,JSON.stringify(next));return next;}async save(config:InstanceConfig){localStorage.setItem('caos:selected-instance',config.INSTANCE_ID);localStorage.setItem(this.key,JSON.stringify(config));}async clear(){localStorage.removeItem(this.key);localStorage.removeItem('caos:selected-instance');}}
