export const CA_OS_VERSION = '0.1.0';
export const CURRENT_SCHEMA_VERSION = 2;

export const TABLE_SCHEMAS: Record<string, string[]> = {
  INSTANCE: ['INSTANCE_ID','INSTANCE_NAME','CA_OS_VERSION','SCHEMA_VERSION','ADMIN_USER_ID','STATUS','CREATED_AT','UPDATED_AT'],
  USERS: ['USER_ID','INSTANCE_ID','EMAIL','DISPLAY_NAME','ROLE','STATUS','CREATED_AT','UPDATED_AT'],
  ORGANISATIONS: ['ID_ORGANISATION','INSTANCE_ID','NOM','TYPE','STATUT','CREATED_AT','UPDATED_AT'],
  AFFAIRES: ['ID_AFFAIRE','INSTANCE_ID','REFERENCE_AFFAIRE','NOM_AFFAIRE','ID_ORGANISATION_CLIENT','DESCRIPTION','ETAT','PHASE','RESPONSABLE_USER_ID','DATE_CREATION','DATE_DEBUT','DATE_FIN_PREVUE','MONTANT','MARGE','AVANCEMENT','ENJEUX','RISQUES','PROCHAINE_ECHEANCE','FIABILITE_INFORMATION','DATE_MODIFICATION','ARCHIVED_AT','CLIENT_NOM'],
  ACTIONS: ['ID_ACTION','INSTANCE_ID','ID_AFFAIRE','TITRE','DESCRIPTION','PRIORITE','STATUT','RESPONSABLE_USER_ID','DATE_CREATION','ECHEANCE','DATE_CLOTURE','WHY','DATE_MODIFICATION','ARCHIVED_AT'],
  DECISIONS: ['ID_DECISION','INSTANCE_ID','ID_AFFAIRE','SUJET','CONTEXTE','OPTIONS','DECISION','JUSTIFICATION','VALIDATEUR_USER_ID','STATUT','DATE_DECISION','DATE_MODIFICATION','ARCHIVED_AT','FAIT','RISQUE','IMPACT','INFORMATION_MANQUANTE','FIABILITE','RECOMMANDATION','ACTION','RESPONSABLE_USER_ID','ECHEANCE'],
  DOCUMENTS: ['DOCUMENT_ID','INSTANCE_ID','ID_AFFAIRE','TITRE','PROVIDER','PROVIDER_FILE_ID','DOCUMENT_URL','DOCUMENT_LOCATION','MIME_TYPE','VERSION','STATUT','DATE_AJOUT','DATE_MODIFICATION','ARCHIVED_AT'],
  CONTACTS: ['ID_CONTACT','INSTANCE_ID','ID_AFFAIRE','ID_ORGANISATION','NOM','PRENOM','EMAIL','TELEPHONE','FONCTION','STATUT','DATE_CREATION','DATE_MODIFICATION','ARCHIVED_AT'],
  EVENEMENTS: ['ID_EVENEMENT','INSTANCE_ID','ID_AFFAIRE','TYPE','TITRE','DESCRIPTION','DATE_EVENEMENT','SOURCE','CREATED_BY_USER_ID','DATE_CREATION','DATE_MODIFICATION','ARCHIVED_AT'],
  CONFIG: ['KEY','VALUE','DESCRIPTION','UPDATED_AT'],
  AUDIT_LOG: ['AUDIT_ID','INSTANCE_ID','WHAT','WHO','WHEN','WHY','SOURCE','ENTITY_TYPE','ENTITY_ID','LEVEL','DETAIL'],
  SCHEMA_VERSION: ['INSTANCE_ID','SCHEMA_VERSION','APPLIED_AT','CA_OS_VERSION'],
  MIGRATIONS: ['MIGRATION_ID','INSTANCE_ID','FROM_VERSION','TO_VERSION','STATUS','APPLIED_AT','DETAIL'],
  ID_COUNTERS: ['ENTITY_PREFIX','INSTANCE_ID','LAST_NUMBER','UPDATED_AT']
};

export const REQUIRED_TABLES = Object.keys(TABLE_SCHEMAS);
export const COUNTER_PREFIXES = ['AFF','ACT','DEC','DOC','CON','EVT','ORG','AUD'];
